######################################################################
# Automatically generated by qmake (2.01a) Mon Dec 13 01:25:08 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h mdichild.h
SOURCES += main.cpp mainwindow.cpp mdichild.cpp
RESOURCES += mdi.qrc
